language: ruby
rvm:
- 2.2.3
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  app:
    master: mysterious-tundra-44113
  api_key:
    secure: IJlM0I1obgbxmujCVK1ctjFd7+ckVyRo2K0UHiga3TbKf5/AdmVcyglQK/+XdTRDTarMzqKEJ/8zdIl6tnq3GAIvJHfBOHGHf3hadF6uieSVYgRnl1/Rky5H74jVkbN7NeSILLMgFjUnsC/yPP0YuGPOOQXWhWCsJreCCqGP+PriCnT2tqt3BZd3cCixn89gdNOKCvKkOYIsJhRlllsr7uQIkwKcZE/pgBhFqZxCoMOsHO5rC5C132EEkNlZbph4+PmamCNktH7sv3jpScKhwYAyn7uaqbmoAneROraQf6rYovbsqWZH8rv8dwr03OGFIskG7klylSbB0/1BM3k2TER8cwa7dUtIswaurAGCi1RWDdw9Q+sHrD9MGHA71EjyNgA9v8WhZOD2/C7rms3RzCWGpJG9flq/9K85Z5VfRKshhd17OGm2YWsAKzcGRSHfvcnTf9TnG2EqyHKZiOiuJBPwMGM1vXBH2bVpAb+7quwj4H4ruwD/RBSgxHHOgHx0e6QoMhvbx5SyS9Soi0sO8ERYP9rd/mODbYzIl5xXK898gJ5A0vUowT3hXIBXTJ5xXbXdR8VDsCKy5MCVQl1ny7KpirkXBEqZjCiutEU0aqRNa2xQ3D+6AKlKNX5EOHIh8MBTpg+tW6i8ZZVgcsyID1VgLWPJi7X75XXWf3XWEFc=
